### ISSUE TITLE
Minimum C++ language standard

### ISSUE THREAD

**Issue by mbkumar** [zhanghe9704/tpsa#11]
In the docs, the minimum C++ language spec is given as C++11. But to compile the examples, C++14 is used. Is the discrepancy due to the usage of C++14 features in examples? Now that all compilers support C++14, I think bumping the minimum spec to C++14 would be a better option.

**Comment by zhanghe9704** [comment]
Yes, the examples use "std::complex_literals", which is a C++ 14 feature. This is the only place that needs C++ 14.

**Comment by zhanghe9704** [comment]
Readme file, CMakeLists, and Makefiles are revised for C++14.

**Comment by mbkumar** [comment]
OK. Sounds reasonable. Closing the issue.
