### ISSUE TITLE
[JOSS Review] Paper references

### ISSUE THREAD

**Issue by CFGrote** [zhanghe9704/tpsa#16]
JOSS Review: https://github.com/openjournals/joss-reviews/issues/4818

- Berz, M (1999): Journal volume and pages missing
- Deniau et al 2017 is the mad-x reference manual, is there a paper that describes the code? mad-x gh repo has a doi, maybe that's better suited as a citation reference?
- Forest et al 2002: no DOI, could add report number "CERN-SL-2002-044-AP" and/or url https://inspirehep.net/literature/591979
- Makino, Berz 2003: This is weird: I find this pdf: https://www.bmtdynamics.org/pub/papers/GOM05/GOM05.pdf, but it's from 2005 (not 2003), Journal is "Transactions on Computers" (not Int. J. of Computer Research), volume, issue, and pages are off, too. Searching for the given citation, nothing  comes back in various citation search engines, except the pdf linked above. Can you clarify, please?
- all other references are fine

**Comment by zhanghe9704** [comment]
- Berz, M (1999) is a book, not a paper. 
- Deniau et al 2017 is replaced by a conference paper and the GitHub repo.
- Forest et al 2002: Link added.
- Makino, Berz 2003 is replaced by the one in 2005. After such a long time, I can't remember how I cited this paper. I also can't find the paper online. I guess this may be a wrong input in my bibtex lib. 
- Add Lingyun Yang's conference paper as a reference to his code.

**Comment by CFGrote** [comment]
Looks good. One final comment on references: Could you try to use a consistent formatting for volume and issue? E.g. in Berz, Makino (1998), volume and issue are given as _4_(4), in Makino, Berz (2005), you use _11, 4_, .

Actually, Berz, Makino (1998) should not have a issue number, only volume. Makino, Berz (2005) is volume 4, issue 11. your formatting does not make it clear which number is volume and which one is issue.

Sorry for being pedantic

**Comment by danielskatz** [comment]
part of https://github.com/openjournals/joss-reviews/issues/4818

**Comment by zhanghe9704** [comment]
Removed the issue number in Berz, Makino (1998) and changed the volume and issue of Makino, Berz (2005) in 11 (4). Thanks a lot for looking into the details.
