### ISSUE TITLE
[JOSS Review] Installation

### ISSUE THREAD

**Issue by CFGrote** [zhanghe9704/tpsa#2]
JOSS Review: https://github.com/openjournals/joss-reviews/issues/4818

When compiling the code (tip of master branch as of today), I get
```
cmake .
-> ok
```

```
make

[ 16%] Building CXX object CMakeFiles/tpsaso.dir/src/da.cc.o
In file included from /usr/include/c++/12/complex:41,
                 from /home/grotec/Repositories/JOSSReviews/tpsa/src/../include/da.h:12,
                 from /home/grotec/Repositories/JOSSReviews/tpsa/src/da.cc:9:
/usr/include/c++/12/complex: In instantiation of ‘std::complex<_Tp> std::polar(const _Tp&, const _Tp&) [with _Tp = DAVector]’:
/usr/include/c++/12/complex:778:29:   required from ‘std::complex<_Tp> std::__complex_exp(const complex<_Tp>&) [with _Tp = DAVector]’
/usr/include/c++/12/complex:793:56:   required from ‘std::complex<_Tp> std::exp(const complex<_Tp>&) [with _Tp = DAVector]’
/home/grotec/Repositories/JOSSReviews/tpsa/src/da.cc:1259:49:   required from here
/usr/include/c++/12/complex:703:7: error: no match for ‘operator>=’ (operand types are ‘const DAVector’ and ‘int’)
  703 |       __glibcxx_assert( __rho >= 0 );
      |       ^~~~~~~~~~~~~~~~
...
```

OS: Debian 12.2 (Kernel 6.1.0-15-amd64)
cmake: 3.25.1
gcc: 12.2.0

**Comment by CFGrote** [comment]
As mentioned in https://github.com/openjournals/joss-reviews/issues/4818, code compiles with gcc-10.2.1.

**Comment by zhanghe9704** [comment]
The compiling error with gcc version above 10.2.1 has been solved. Now the code compiles with gcc 12.2.

The error is due to the newer gcc compiler cannot handle the exp() function for complex DA vectors. 
Explicitly defining the exp() function solved the problem.

**Comment by danielskatz** [comment]
👋 @zhanghe9704 & @CFGrote - can this issue now be closed?

**Comment by CFGrote** [comment]
Yes, @zhanghe9704 ,please close
