### ISSUE TITLE
[JOSS Review] Testing on Linux

### ISSUE THREAD

**Issue by CFGrote** [zhanghe9704/tpsa#3]
https://github.com/openjournals/joss-reviews/issues/4818

As mentioned in the README, running the tests produces a segmentation fault although all tests pass.

OS: Debian-12
gcc: 10.2.1

Built tpsa code and test executable according to instructions (README.md).
```
▶ ./tests
===============================================================================
All tests passed (21 assertions in 3 test cases)

[1]    416166 segmentation fault  ./tests
```

Although the README says this is a known issue and does not seem to affect the code in production setting, I'd still strongly suggest to fix this. Observing segfaults in a test may keep potential users from adopting the library in their code (at least judging for myself). I guess the root cause lies in the test framework.

**Comment by zhanghe9704** [comment]
The TPSA lib will allocate a memory pool to handle the DA vector
calculations and release it before quitting.
I suspect this process conflicts with the way in which CATCH2 manages the
memory. That's why I left it as is with a note in the readme.
I'll try to fix it.

Thanks.

**Comment by CFGrote** [comment]
Seems to be fixed now, thanks!
