### ISSUE TITLE
[JOSS Review] Documentation is README.md (only)

### ISSUE THREAD

**Issue by CFGrote** [zhanghe9704/tpsa#4]
https://github.com/openjournals/joss-reviews/issues/4818

Upon first glance, the documentation is limited to the repository top level README.md. There is a doc directory with doxygen content but no instruction how to build it (does it have to be built or is it included with the repo?) how is it maintained if the API changes?

I suggest using some flavor of CI/CD to build the code and the documentation (e.g. github actions and github pages) to make documentation available as a website on its own rather than a local collection of html files.

Doing so would also check the box Documentation - Functionality Documentation (API)

**Comment by zhanghe9704** [comment]
Currently, the doxygen files are generated locally by hand and pushed to
the github repository.

I agree it's a good idea to use github actions and github pages for
documentation. I'll look into it.

Thanks.

**Comment by zhanghe9704** [comment]
Now the doxygen files are generated automatically when pushing to the main branch.  All the documents (readme, contributing guideline, doxygen) can be accessed via https://zhanghe9704.github.io/tpsa/. The webpage is also deployed automatically when pushing to the main branch. All these are done using GitHub Actions, controlled by the yml files in .github/workflow.

**Comment by danielskatz** [comment]
👋 @CFGrote - can this issue now be closed?

**Comment by CFGrote** [comment]
closing as fixed by 889eb9e7e61f1adc1a417d632596fc66c2e29289 and other commits.
