### ISSUE TITLE
[JOSS Review] Documentation - Community Guidelines

### ISSUE THREAD

**Issue by CFGrote** [zhanghe9704/tpsa#6]
https://github.com/openjournals/joss-reviews/issues/4818

Community guidelines are missing (beyond the author's contact email). You may want to take advantage of github's instructions (go Insights -> Community Standards -> Contributing) in the repos' menu) and/or consult JOSS's documentation on this topic at https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines

**Comment by zhanghe9704** [comment]
Guidelines are added here:https://github.com/zhanghe9704/tpsa/blob/master/.github/CONTRIBUTING.md 
The link is also added to "readme.md" in the root folder.
