### ISSUE TITLE
[JOSS Review] License

### ISSUE THREAD

**Issue by CFGrote** [zhanghe9704/tpsa#7]
https://github.com/openjournals/joss-reviews/issues/4818

I see an issue with the Open Source License (OSL) and the inclusion of non open source code in the repository: include/tpsa.h and src/tpsa.cpp
have been copied from the MAD-X code and are distributed with this repository, licensed under MIT. On the other hand, the two  source files are copyright to L. Yang, not licensed under any OSL, and distributors are asked to request L. Yang's consent prior to redistribution. In my view this is not compatible with OS Licensing, certainly not ok to put the entire repo under MIT.

I see these two solutions to the problem
1: Ask L. Yang to release his code under OS License and include or redistribute in this repo
2: Remove L. Yang's code from this repo and instruct users how to obtain it, including request for consent by L. Yang.

In my view this is blocking a release under OSL and violating JOSS' terms of publication.

**Comment by zhanghe9704** [comment]
Contacted L. Yang. He agree to put his code under MIT license. 
Copyright announcement was revised respectively.

**Comment by CFGrote** [comment]
Excellent, thanks!
