### ISSUE TITLE
CMake install step not installing the header files

### ISSUE THREAD

**Issue by mbkumar** [zhanghe9704/tpsa#8]
When I do cmake install, only the lib is installed and not the header files. 

When I run the below commands 
```bash
cmake -S. -Bbuild -DCMAKE_INSTALL_PREFIX=<install_location>
cd build
make
make install
```
only the library files are installed at `<install_location>/lib` and the header files are missing. Header files need to be installed in `<install_location>/include` when I run the `make install` command. 

Could you please fix this?

**Comment by zhanghe9704** [comment]
Now the header file is installed.
