### ISSUE TITLE
Hard coded header file location in examples/examples.cc

### ISSUE THREAD

**Issue by mbkumar** [zhanghe9704/tpsa#9]
The header file location is hard coded in examples/examples.cc.
Line 1 in examples.cc should contain `#include "da.h"`. The location of the header files is then specified in the command line using the `-I` flag.

The command 
```
gcc examples/examples.cc -o tpsa_exp -I ./include/ -L. -ltpsa -lstdc++ -lm -std=c++14
``` 
should be modified to
```
gcc examples/examples.cc -o tpsa_exp -I<cmake_install_prefix>/include/ -L<cmake_install_prefix>/lib -ltpsa -lstdc++ -lm -std=c++14
```

**Comment by zhanghe9704** [comment]
Both the make files for the examples and tests are changed as advised. They now can be compiled by run the make command in the respective folder or run the following cmake command in the root folder: 
cmake --build . --target build_examples
cmake --build . --target build_tests
